name: Danilo Reis
description: A descrição do blog aqui
meta_description: ""

markdown: kramdown
highlighter: pygments
logo: false
paginate: 15
baseurl: ""
domain_name: 'http://yourblog-domain.com'
google_analytics: 'UA-XXXXXXXX-X'
gems: [jekyll-paginate]

# Links Bases
links:
  - title: Home
    url: /
    baseurl: /
    
    
# Details for the RSS feed generator
url:            'http://idaniloreis.github.io'
author:         'Danilo Reis'

# Definindo o Permalink
permalink: /:title/

